/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ombheri;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.AbstractAction;
import javax.swing.Action;
/**
 *
 * @author Lanaya
 */

public class custForm extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    String regMain;

    int a;
    String text;
    sqlConn sqlcon=new sqlConn();
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    LocalDate localDate = LocalDate.now();
    String dat;
    
    
    Action action = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
//            System.out.println("some action");
            saveActionPerformed(e);
            
        }
    };
    
    public void generate(){
        regno.setText(text);
        date.setText(dat);
    }
    
    public void lastReg(){
        String sql="SELECT regno FROM customer ORDER BY regno DESC LIMIT 1;";
        try{
            ResultSet rs=sqlcon.stmt.executeQuery(sql);
            
            if(rs.next()){
                a=rs.getInt(1)+1;
                
            } 
            else 
                a=1;
            
        }catch(Exception e){
            System.out.println(e);
        }
        text=(Integer.toString(a));
    }
    public custForm() {
//        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 

//        System.out.println(dtf.format(localDate)); //2016/11/16
        dat=dtf.format(localDate);
        this.lastReg();
        
            
        initComponents();
        this.setTitle("New Entry");
        firstn.addActionListener(action);
        lastn.addActionListener(action);
        addr.addActionListener(action);
        contno.addActionListener(action);
        age.addActionListener(action);
//        firstn.addActionListener(action);
        
//        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                procedureCall();
            }
        });        
    }
    public  void procedureCall(){
        this.dispose();
        front f=new front();
        f.setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lastn = new javax.swing.JTextField();
                addr = new javax.swing.JTextField();
                firstn = new javax.swing.JTextField();
                regno = new javax.swing.JTextField();
                contno = new javax.swing.JTextField();
                age = new javax.swing.JTextField();
                date = new javax.swing.JTextField();
                save = new javax.swing.JButton();
                cancel = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(1100, 650));
                setResizable(false);

                lastn.setBackground(new java.awt.Color(255, 255, 0));
                lastn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                lastn.setForeground(new java.awt.Color(0, 102, 255));
                lastn.setText("Last Name");
                lastn.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                lastnFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                lastnFocusLost(evt);
                        }
                });
                lastn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lastnActionPerformed(evt);
                        }
                });

                addr.setBackground(new java.awt.Color(255, 255, 0));
                addr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                addr.setForeground(new java.awt.Color(0, 102, 255));
                addr.setText("Address");
                addr.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                addrFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                addrFocusLost(evt);
                        }
                });

                firstn.setBackground(new java.awt.Color(255, 255, 0));
                firstn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                firstn.setForeground(new java.awt.Color(0, 102, 255));
                firstn.setText("First Name");
                firstn.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                firstnFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                firstnFocusLost(evt);
                        }
                });
                firstn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                firstnActionPerformed(evt);
                        }
                });

                regno.setBackground(new java.awt.Color(255, 255, 0));
                regno.setForeground(new java.awt.Color(0, 102, 255));
                regno.setToolTipText("");
                regno.setFocusable(false);
                regno.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                regnoFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                regnoFocusLost(evt);
                        }
                });
                regno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                regnoActionPerformed(evt);
                        }
                });

                contno.setBackground(new java.awt.Color(255, 255, 0));
                contno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                contno.setForeground(new java.awt.Color(0, 102, 255));
                contno.setText("Contact no.");
                contno.setToolTipText("");
                contno.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                contnoFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                contnoFocusLost(evt);
                        }
                });
                contno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                contnoActionPerformed(evt);
                        }
                });

                age.setBackground(new java.awt.Color(255, 255, 0));
                age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                age.setForeground(new java.awt.Color(0, 102, 255));
                age.setText("Age");
                age.setToolTipText("");
                age.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                ageFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                ageFocusLost(evt);
                        }
                });
                age.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ageActionPerformed(evt);
                        }
                });

                date.setEditable(false);
                date.setBackground(new java.awt.Color(255, 255, 0));
                date.setForeground(new java.awt.Color(0, 102, 255));
                date.setToolTipText("");
                date.setFocusable(false);
                date.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                dateFocusGained(evt);
                        }
                });
                date.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dateActionPerformed(evt);
                        }
                });

                save.setBackground(new java.awt.Color(255, 255, 102));
                save.setForeground(new java.awt.Color(0, 102, 255));
                save.setText("Save");
                save.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveActionPerformed(evt);
                        }
                });

                cancel.setBackground(new java.awt.Color(255, 255, 102));
                cancel.setForeground(new java.awt.Color(0, 102, 255));
                cancel.setText("Cancel");
                cancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelActionPerformed(evt);
                        }
                });

                jLabel1.setBackground(new java.awt.Color(255, 255, 102));
                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 102, 255));
                jLabel1.setText("Registration no.");

                jLabel2.setBackground(new java.awt.Color(255, 255, 102));
                jLabel2.setForeground(new java.awt.Color(0, 102, 255));
                jLabel2.setText("Date");

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(0, 102, 255));
                jLabel8.setText("New Entry");
                jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(addr)
                                                .addGap(530, 530, 530))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(143, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(contno)
                                                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(68, 68, 68))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(save)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(cancel)
                                                                .addGap(94, 94, 94))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(firstn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lastn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lastn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(45, 45, 45)
                                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(110, 110, 110)
                                                .addComponent(contno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancel)
                                        .addComponent(save))
                                .addGap(93, 93, 93))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void lastnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnActionPerformed

    private void firstnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnFocusGained
        // TODO add your handling code here:
        
        firstn.setBackground(Color.YELLOW);
        if(firstn.getText().equals("First Name")){
            firstn.setText("");
        }
    }//GEN-LAST:event_firstnFocusGained

    private void lastnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnFocusGained
        // TODO add your handling code here:
	lastn.setBackground(Color.YELLOW);
        if(lastn.getText().equals("Last Name")){
            lastn.setText("");
        }
    }//GEN-LAST:event_lastnFocusGained

    private void addrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrFocusGained
        // TODO add your handling code here:  
	addr.setBackground(Color.YELLOW);
        if(addr.getText().equals("Address")){
            addr.setText("");
        }
    }//GEN-LAST:event_addrFocusGained

    private void firstnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnFocusLost
        // TODO add your handling code here:
        if(firstn.getText().equals("")){
            firstn.setText("First Name");
        }
    }//GEN-LAST:event_firstnFocusLost

    private void lastnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnFocusLost
        // TODO add your handling code here:
        if(lastn.getText().equals("")){
            lastn.setText("Last Name");
        }
    }//GEN-LAST:event_lastnFocusLost

    private void addrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addrFocusLost
        // TODO add your handling code here:
        if(addr.getText().equals("")){
            addr.setText("Address");
        }
    }//GEN-LAST:event_addrFocusLost

    private void regnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoFocusGained

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained
        // TODO add your handling code here:
	age.setBackground(Color.YELLOW);
        if(age.getText().equals("Age")){
            age.setText("");
        }
    }//GEN-LAST:event_ageFocusGained

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        // TODO add your handling code here:
        

    }//GEN-LAST:event_dateFocusGained

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void contnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contnoActionPerformed

    private void contnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contnoFocusGained
        // TODO add your handling code here:
	contno.setBackground(Color.YELLOW);
        if(contno.getText().equals("Contact no.")){
            contno.setText("");
        }
    }//GEN-LAST:event_contnoFocusGained

    private void firstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnActionPerformed


    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        front f=new front();
        f.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    public boolean isNumeric(String str) {
	try {  
	  Double.parseDouble(str);  
	  return true;
	} catch(NumberFormatException e){  
	  return false;  
	}  
     }
    
    public boolean isAlpha(String name) {
	return name.matches("[a-zA-Z]+");
    }
    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
	
	// Checking if data are valid
	boolean error = false;
	if(this.isNumeric(contno.getText())){	   
		if (contno.getText().length() != 9 && contno.getText().length() != 10 && contno.getText().length() != 13){
			contno.setBackground(Color.RED);
			error = true;
		}
	}
	else{
		contno.setBackground(Color.RED);
	}
	
	if (firstn.getText().length() == 0 || firstn.getText().equals("First Name") || !this.isAlpha(firstn.getText())){
		firstn.setBackground(Color.RED);
		error = true;
	}
	if (lastn.getText().length() == 0 || lastn.getText().equals("Last Name") || !this.isAlpha(lastn.getText())){
		lastn.setBackground(Color.RED);
		error = true;
	}
	if (age.getText().length() == 0 || age.getText().equals("Age") || !this.isNumeric(age.getText())){
		age.setBackground(Color.RED);
		error = true;
	}
	if (addr.getText().length() == 0 || addr.getText().equals("Address")){
		addr.setBackground(Color.RED);
		error = true;
	}
	if (error){
		String message = "\"Please enter valid data\"\n";
		JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
		JOptionPane.ERROR_MESSAGE);
		return;
	}
	        
        String sql="insert into customer (date,regno,firstn,lastn,age,contno,addr)values('"+date.getText()+"',"+regno.getText()+",'"+firstn.getText()+"','"+lastn.getText()+"',"+age.getText()+","+contno.getText()+",'"+addr.getText()+"');";
        try{
            sqlcon.stmt.executeUpdate(sql);
            System.out.println("Successfully entered data");
            this.dispose();
            JOptionPane.showMessageDialog(null, "Successfully entered data");
            
            front f=new front();
            f.setVisible(true);
            
        }catch(SQLIntegrityConstraintViolationException s){
            System.out.println(s);
            String message = "\"Data field is default or empty.\"\n"
            + "\"If above field are correct then Register no may be already taken\"\n";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
            JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
        System.out.println(e);
//            JOptionPane.showMessageDialog(frame, "Data entered is incorrect or empty ");
//            JOptionPane.showMessageDialog(frame, "Eggs are not supposed to be green.");
        String message = "\"Data entered is incorrect or empty\"\n"
        + "\"Check for default value or wrong data type\"\n";
        JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
        if(age.getText().equals("")){
            age.setText("Age");
        }
    }//GEN-LAST:event_ageFocusLost

    private void contnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contnoFocusLost
        // TODO add your handling code here:
        if(contno.getText().equals("")){
            contno.setText("Contact no.");
        }
    }//GEN-LAST:event_contnoFocusLost

    private void regnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnoFocusLost
        // TODO add your handling code here:
        regno.setFocusable(false);
    }//GEN-LAST:event_regnoFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(custForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(custForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(custForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(custForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new custForm().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField addr;
        private javax.swing.JTextField age;
        private javax.swing.JButton cancel;
        private javax.swing.JTextField contno;
        private javax.swing.JTextField date;
        private javax.swing.JTextField firstn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JTextField lastn;
        private javax.swing.JTextField regno;
        private javax.swing.JButton save;
        // End of variables declaration//GEN-END:variables
}
